config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
  resources :products
  get 'search', to: "products#search", as: :search
  post 'import_data', to: "products#import_data", as: :import_data
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  require 'csv'
  belongs_to :user

  validates :name, :price, presence: true

  def self.import(file_name, user)
    file_path = File.join("public/import_data", file_name)
    file = File.open(file_path, 'r')

    CSV.foreach(file, headers: true) do |row|
      Product.create!(row.to_h.merge(user_id: user.id))
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'fileutils'
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = current_user.products
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        flash[:sucess] = 'Create Sucessfully'
        format.js
        format.json { render json: @product, status: 200 }
      else
        format.js { render 'new' }
        format.json { render json: @product, status: 500 }
      end
      @products = current_user.products
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:sucess] = 'Update Sucessfully'
    else
      flash[:error] = @product.errors.messages
    end
    @products = current_user.products
  end

  def destroy
    if @product.destroy
      flash[:sucess] = 'Delete Sucessfully'
    else
      flash[:error] = @product.errors.messages
    end
    @products = current_user.products
  end

  def import_data
    dir = File.join Rails.root, 'public', 'import_data'
    FileUtils.mkdir_p(dir) unless File.exist?(dir)

    file_name = params[:import_file].original_filename
    file = File.join("public/import_data", file_name)
    uploaded_file = params[:import_file]

    File.open(file, 'wb') do |file|
      file.write(uploaded_file.read)
    end

    # CSV upload into database using backgound job
    ImportCsvDataForProductJob.perform_later(file_name, current_user)
    redirect_to products_path
  end

  def search
    @products = if params[:search].present?
                  current_user.products.where('name LIKE ?', "%#{params[:search]}%")
                else
                  current_user.products
                end
  end

  private
  def set_product
    @product = current_user.products.find_by_id(params[:id])
    redirect_to root_path, error: 'Product not exist Or You are not allowed to access the product' unless @product.present?
  end

  def product_params
    params.require(:product).permit(:name, :price, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Welcom To Simform Practical</h1>
  <ul>
    <li> User Sign up & Sign in </li>
    <li> User Can perform CURD opration on product </li>
    <li> User upload bluk of record for product </li>
  </ul>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: black !important">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3FnCew1aaKfK4mRFX0RnWabPCMyv1ambJW0Hsh_enKmDHt4dvyrehZ9YGDe2GZOfJoK8&usqp=CAU" style="width: 3%">
    <ul class="navbar-nav ml-auto my-2 my-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

      <% if current_user %>
        <li class="nav-item active"> <%= link_to 'Products', products_path, class: "nav-link"  %> </li>
        <li class="nav-item active"> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete , class: "nav-link" %>  </li>
      <% else %>
         <li class="nav-item active"> <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"  %>  </li>
         <li class="nav-item active"> <%= link_to 'Sign In', new_user_session_path , class: "nav-link" %>  </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name,  class: "form-control"%>
</div>
<div class="form-group">
  <%= f.label :price %>
  <%= f.text_field :price,  class: "form-control"%>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description,  class: "form-control"%>
</div>

app/views/products/_import_csv_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="csvModal" tabindex="-1" role="dialog" aria-labelledby="csvModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_with url: import_data_path, local: true, 'multip-part': true do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="csvModalLabel">Import CSV for product</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.file_field :import_file %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit  class:"btn btn-primary"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_listing.html.erb
<% if products.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% products.each do |product| %>
        <tr>
          <th scope="row">pro-<%= product.id %></th>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td>
            <%= link_to product_path(product) do  %>
              <i class="fa fa-eye"></i>
            <% end %>
            <%= link_to edit_product_path(product), remote: true do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to product_path(product), method: :delete, remote: true  do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No product yet!!!
<% end %>

app/views/products/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="productModal" tabindex="-1" role="dialog" aria-labelledby="productModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_with model: product, remote: true do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="productModalLabel">Edit</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul>
            <% product.errors.messages.each do |k,v| %>
              <li class='text-danger'><%= k %> <%= v.join(',') %></li>
            <% end %>
          </ul>
          <% product.errors.messages.each do |k,v| %>
          <% end %>
          <%= render partial: 'form', locals: { f: f } %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit  class:"btn btn-primary"%>
          <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/create.js.erb
$('#productModal').modal('hide')
$('#product_listing').html("<%= j(render partial: 'listing', locals: { products: @products }) %>")

app/views/products/destroy.js.erb
$('#product_listing').html("<%= j(render partial: 'listing', locals: { products: @products }) %>")

app/views/products/edit.js.erb
$('#createEditProduct').html("<%= j(render partial: 'modal', locals: {product: @product} ) %>")
$('#productModal').modal('show')

app/views/products/index.html.erb
<h1>Product List</h1><br>

<%= link_to 'Create New Product', new_product_path, remote: true %> <br>
<%= link_to 'Import CSV', 'javascript:void(0)', data: {toggle: "modal", target: "#csvModal" } %> <br><br>

<!-- Search -->
<%= form_with url: search_path, remote: true, method: :get do |f| %>
  <%= f.text_field :search, class: "search" %>
  <i class="fa fa-times fa-lg search-data"></i>

  <%= f.submit 'Search' , class: 'btn btn-success ml-2' %>
<% end %>
<br><br>

<!-- Listing -->
<div id="product_listing">
  <%= render partial: 'listing', locals: { products: @products } %>
</div>

<div id='createEditProduct'></div>
<%= render 'import_csv_modal' %>

<script>
  searchData()
</script>

app/views/products/new.js.erb
$('#createEditProduct').html("<%= j(render partial: 'modal', locals: {product: @product} ) %>")
$('#productModal').modal('show')

app/views/products/search.js.erb
$('#product_listing').html("<%= j(render partial: 'listing', locals: { products: @products }) %>")

app/views/products/show.html.erb
<h1> <%= @product.name %> </h1>
Created At: <%= @product.created_at %>
<br><br>
<h4> Rs. <%= @product.price %> </h4>
<p> <%= @product.description %> </p>

<%= link_to "Go Back", products_path %>

app/views/products/update.js.erb
$('#productModal').modal('hide')
$('#product_listing').html("<%= j(render partial: 'listing', locals: { products: @products }) %>")